### PR TITLE
Updating JSON formats

### LINKED ISSUE #92: Contributors' Timeline
It has been pointed out to me that not all of the actual contributions made to the entire VITacademics system are being represented fairly (API Server, Client Apps, Design etc.) except in Copyright Notices present in this project. 

After all, we would not want anybody's contribution to be overlooked and we also want to maintain consistency among the client apps, which are also the user-facing components of the system. 

For this, an endpoint for listing out all the contributors and their details of the VITacademics system needs to be implemented.

### PR DESCRIPTION
**Pull request by aneesh-neelam**
I have devised a way to unify the JSON formats for Marks of all course types and also generalize the Grades Summary in the Grades JSON. 

As you can see in the refresh sample-data [here](https://github.com/aneesh-neelam/VITacademics/blob/staging/api/sample-data/api-refresh.json), I have implemented a unified Marks JSON format for CBL, LBC, PBC and PBL/RBL course types.  

Also, as you can see in the grades sample-data [here](https://github.com/aneesh-neelam/VITacademics/blob/staging/api/sample-data/api-grades.json), I have implemented a general format for Grade Summary, or Grade Count as it is now called. 

This greatly simplifies JSON parsing and storing data on the device, especially when using Mantle on iOS and/or GSON + Sugar on Android. 

Added list of contributors for System Endpoint. Fixes #92. 

This branch is also deployed on [vitacademics-staging.herokuapp.com](https://vitacademics-staging.herokuapp.com/). 

Also, I have enabled automatic deploys on Heroku, so merge this only when you're ready to see it on [vitacademics-rel.herokuapp.com](https://vitacademics-rel.herokuapp.com/). 

@biocross, @VinayGupta23: Please update your JSON parsing code in your respective apps. You can use [vitacademics-staging.herokuapp.com](https://vitacademics-staging.herokuapp.com/) for that.

### CODE REVIEW

**Comment by aneesh-neelam** [comment]
@biocross, @VinayGupta23: You guys must move to this JSON format as soon as possible.

You can use [vitacademics-staging.herokuapp.com](https://vitacademics-staging.herokuapp.com/) until all client app updates are pushed.

**Comment by biocross** [comment]
I am done with this. I'll let you know when I update the app on the appstore.

**Comment by VinayGupta23** [comment]
Ah damn.
Will get to it soon...
It's already on rel? Don't tell me.

Btw it was a good idea to unify that.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
It's not on [vitacademics-rel](https://vitacademics-rel.herokuapp.com/). It will be when this Pull Request, #91 gets merged. For now this is on [vitacademics-staging](https://vitacademics-staging.herokuapp.com/)

**Comment by VinayGupta23** [comment]
Okay cool.
Let me know before its getting on rel.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
You can push app updates that use [vitacademics-staging.herokuapp.com](https://vitacademics-staging.herokuapp.com/). I've configured that for production use. 

However, when both client apps are ready and pushed, I'll also update [vitacademics-rel.herokuapp.com](https://vitacademics-rel.herokuapp.com/)

**Comment by VinayGupta23** [comment]
Oh nice.
Ill get on it soon.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
@biocross, @VinayGupta23: Update! Grades too. 

As you can see in the grades sample-data [here](https://github.com/aneesh-neelam/VITacademics/blob/staging/api/sample-data/api-grades.json), I have implemented a general format for Grade Summary, or Grade Count as it is now called.

**Pull request merged**
