### PR TITLE
Updated API for Winter Semester

### PR DESCRIPTION
**Pull request by ashwini0529**
[Review on Reviewable](https://reviewable.io/reviews/aneesh-neelam/vitacademics/122)

### CODE REVIEW

**Comment by ashwini0529** [comment]
Can you please provide me the commit in which it is updated?

**Comment by ayushagarwal95** [comment]
Try sending a request to the release application on Heroku, it shows Winter Semester details now.
Also, it is done here: b717fa88f45bed7835ea30ccc0476e58c93e3f8d

**Comment by aneesh-neelam** [comment]
@ayushagarwal95: This wasn't necessary, it can be done via environment variables. The semester in the JavaScript code is just for reference.

**Comment by ayushagarwal95** [comment]
I change it in config.js as well so that I can test it on local host.

**Pull request closed without merging**
