### PR TITLE
Using a single router instance

### PR DESCRIPTION
**Pull request by ghost**
Using a single router created in app.js and passing them to the routes because "less is better"

### CODE REVIEW

**Comment by aneesh-neelam** [comment]
This on the wrong branch.

**Comment by karthikb351** [comment]
It's a lot more modular if we use different routers.

And a router is just a tiny middleware.

Multiple small middleware vs one big one don't make much of a difference.

And tomorrow, if we want to enforce a new policy on a subset of routes, we could just do it to that router.
It's far more manageable.

**Comment by aneesh-neelam** [comment]
@aashrairavooru: Check [this](http://expressjs.com/guide/routing.html) out.

**Comment by aneesh-neelam** [comment]
What you did created duplicated handlers for the same route. For example '/' has multiple handler functions assigned. Since the Express.js router is a single dimension array, the first handler in the list will be chosen. 

Also the wrong handlers are assigned to the URL Paths, especially the ones which are namespaced in separate files. 

The following URLs all point to the System API Endpoint, this handler is encountered first when going through the URL stack: 
- /
- /api/txtweb
- /api/v2/system
- /api/v2/vellore
- /api/v2/chennai

If you want to use a single router instance, you must put all the handlers in a single file and you cannot use url namespacing in this case. 

@aashrairavooru: Check [this](http://expressjs.com/guide/routing.html) out. Using a single router instance means using a single router file. 

Why don't you `console.log(app._router.stack)` at the end of `app.js` and see.

**Pull request closed without merging**
